# Generated by Django 5.0 on 2023-12-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.doctor'),
        ),
    ]
