# Generated by Django 5.0 on 2023-12-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_alter_doctor_user'),
        ('med', '0004_patients_doctor'),
    ]

    operations = [
    ]
